# frozen_string_literal: true

RSpec.describe Kettle::Jem, "appraisal helpers and template tokens" do
  include_context "with isolated kettle-jem environment"
  include_context "with kettle-jem fixture contracts"

  it "renders deterministic appraisal helper outputs" do
    matrix_entries = [
      {
        name: described_class.appraisal_name(
          tier1_gem: "activerecord",
          tier1_version: "7.1",
          tier2_gem: "omniauth",
          tier2_version: "2.1",
          ruby_series: "r3"
        ),
        ruby_series: "r3",
        tier1_gemfile: "gemfiles/modular/activerecord/r3/v7.1.gemfile",
        tier2_gemfile: "gemfiles/modular/omniauth/r3/v2.1.gemfile",
        x_std_libs_gemfile: "gemfiles/modular/x_std_libs/r3/libs.gemfile"
      },
      {
        name: described_class.appraisal_name(
          tier1_gem: "mail",
          tier1_version: "2.8",
          ruby_series: "r2"
        ),
        ruby_series: "r2",
        tier1_gemfile: "gemfiles/modular/mail/r2/v2.8.gemfile",
        x_std_libs_gemfile: "gemfiles/modular/x_std_libs/r2/libs.gemfile"
      }
    ]
    bucket_ranges = {
      "r2" => {floor: "2.7", ceiling: "2.99"},
      "r3" => {floor: "3.2", ceiling: "3.99"}
    }

    expect(described_class.appraisal_gem_abbreviation("activerecord")).to eq("ar")
    expect(described_class.appraisal_gem_abbreviation("unknown")).to eq("unknown")
    expect(described_class.appraisal_format_version("7.1.5")).to eq("7-1-5")
    expect(matrix_entries.map { |entry| entry.fetch(:name) }).to eq(["kja-ar-7-1-oa-2-1-r3", "kja-mail-2-8-r2"])
    expect(described_class.appraisal_modular_gemfile_path(gem_name: "activerecord", version: "7.1", ruby_series: "r3")).to eq(
      "gemfiles/modular/activerecord/r3/v7.1.gemfile"
    )
    expect(described_class.appraisal_modular_gemfile_content(
      gem_name: "activerecord",
      version: "7.1",
      sub_dependencies: {"sqlite3" => "1.6.9"}
    )).to eq(<<~RUBY)
      # frozen_string_literal: true

      # Generated by kettle-jem

      gem "activerecord", "~> 7.1.0"
      gem "sqlite3", "~> 1.6.9"
    RUBY

    appraisals = described_class.appraisal_file_content(matrix_entries)
    expect(appraisals).to include('appraise "kja-ar-7-1-oa-2-1-r3" do')
    expect(appraisals).to include('eval_gemfile "modular/activerecord/r3/v7.1.gemfile"')
    expect(appraisals).not_to include('eval_gemfile "gemfiles/')
    expect(appraisals).to include('appraise "kja-mail-2-8-r2" do')
    expect(appraisals).not_to end_with("\n\n")

    groups = described_class.appraisal_workflow_groups(matrix_entries, bucket_ranges: bucket_ranges)
    expect(groups).to eq(
      "supported" => [
        {
          ruby: "3.2",
          appraisal: "kja-ar-7-1-oa-2-1-r3",
          exec_cmd: "kettle-test",
          rubygems: "latest",
          bundler: "latest"
        }
      ],
      "unsupported" => [
        {
          ruby: "2.7",
          appraisal: "kja-mail-2-8-r2",
          exec_cmd: "kettle-test",
          rubygems: "latest",
          bundler: "latest"
        }
      ]
    )
    expect(described_class.appraisal_workflow_yaml_snippets(matrix_entries, bucket_ranges: bucket_ranges).fetch("supported")).to include(
      'appraisal: "kja-ar-7-1-oa-2-1-r3"'
    )
    expect(described_class.appraisal_x_stdlib_exclusions(<<~RUBY)).to eq(["erb", "mutex_m", "version_gem"])
      eval_gemfile "../erb/vHEAD.gemfile"
      eval_gemfile "../mutex_m/vHEAD.gemfile"
    RUBY
  end

  it "plans deterministic appraisal matrices from supplied version metadata" do
    versions = %w[5.0.0 5.1.0 5.2.0 6.0.0 6.1.0 7.0.0 7.1.0 7.2.0].map do |number|
      {number: number}
    end

    expect(described_class.appraisal_select_versions(versions, mode: "major")).to eq(["5.2", "6.1", "7.2"])
    expect(described_class.appraisal_select_versions(versions, mode: "minor")).to eq(
      ["5.0", "5.1", "5.2", "6.0", "6.1", "7.0", "7.1", "7.2"]
    )
    expect(described_class.appraisal_select_versions(versions, mode: "patch")).to eq(
      ["5.0.0", "5.1.0", "5.2.0", "6.0.0", "6.1.0", "7.0.0", "7.1.0", "7.2.0"]
    )
    expect(described_class.appraisal_select_versions(versions, mode: "minor-minmax")).to eq(
      ["5.0", "5.2", "6.0", "6.1", "7.0", "7.1", "7.2"]
    )
    expect(described_class.appraisal_select_versions(versions, mode: "semver")).to eq(["5.2", "6.1", "7.0", "7.1", "7.2"])
    expect(described_class.appraisal_select_versions(versions, mode: "minor", requirements: [">= 6.0", "< 7.0"])).to eq(["6.0", "6.1"])

    entries = described_class.appraisal_matrix_entries(
      tier1_gems: [
        {
          name: "activerecord",
          assignments: [
            {version: "6.1", bucket: "r2"},
            {version: "7.2", bucket: "r3"}
          ]
        }
      ],
      tier2_gems: [
        {name: "omniauth", versions: ["2.1"]}
      ]
    )

    expect(entries).to eq(
      [
        {
          name: "kja-ar-6-1-oa-2-1-r2",
          tier1_gemfile: "gemfiles/modular/activerecord/r2/v6.1.gemfile",
          tier2_gemfile: "gemfiles/modular/omniauth/r2/v2.1.gemfile",
          x_std_libs_gemfile: "gemfiles/modular/x_std_libs/r2/libs.gemfile",
          ruby_series: "r2"
        },
        {
          name: "kja-ar-7-2-oa-2-1-r3",
          tier1_gemfile: "gemfiles/modular/activerecord/r3/v7.2.gemfile",
          tier2_gemfile: "gemfiles/modular/omniauth/r3/v2.1.gemfile",
          x_std_libs_gemfile: "gemfiles/modular/x_std_libs/r3/libs.gemfile",
          ruby_series: "r3"
        }
      ]
    )
  end

  it "detects appraisal Ruby seams and assigns selected versions to buckets" do
    versions = [
      {number: "5.2.8", min_ruby: "2.3"},
      {number: "6.0.6", min_ruby: "2.5"},
      {number: "6.1.7", min_ruby: "2.5"},
      {number: "7.0.8", min_ruby: "2.7"},
      {number: "7.1.5", min_ruby: "2.7"},
      {number: "7.2.2", min_ruby: "3.1"}
    ]

    seams = described_class.appraisal_find_ruby_seams(versions)
    expect(seams).to eq(
      [
        {version: "5.2", min_ruby: Gem::Version.new("2.4")},
        {version: "6.0", min_ruby: Gem::Version.new("2.5")},
        {version: "7.0", min_ruby: Gem::Version.new("2.7")},
        {version: "7.2", min_ruby: Gem::Version.new("3.1")}
      ]
    )

    series = described_class.appraisal_ruby_series(versions)
    expect(series.fetch(:buckets)).to eq(["r2.4", "r2.6", "r2", "r3"])

    assignments = described_class.appraisal_assign_version_buckets(
      selected_versions: ["5.2", "6.1", "7.2"],
      seams: seams,
      buckets: series.fetch(:buckets),
      bucket_ranges: series.fetch(:bucket_ranges),
      all_versions: ["5.2", "6.0", "6.1", "7.0", "7.1", "7.2"]
    )
    expect(assignments).to eq(
      [
        {version: "5.2", bucket: "r2.4"},
        {version: "6.1", bucket: "r2.6"},
        {version: "7.1", bucket: "r2", filler: true},
        {version: "7.2", bucket: "r3"}
      ]
    )
  end

  it "resolves appraisal sub-dependencies from supplied metadata" do
    resolved = described_class.appraisal_resolve_sub_dependencies(
      parent_gem: "activerecord",
      parent_version: "7.1",
      ruby_min: "3.0",
      excluded_gems: ["erb", "version_gem"],
      parent_versions: [
        {
          number: "7.1.3",
          runtime_dependencies: [
            {name: "sqlite3", requirements: "~> 1.6"},
            {name: "erb", requirements: ">= 0"}
          ]
        }
      ],
      dependency_versions: {
        "sqlite3" => [
          {number: "1.6.8", min_ruby: "2.7"},
          {number: "1.6.9", min_ruby: "3.0"},
          {number: "1.7.0", min_ruby: "3.2"}
        ]
      }
    )

    expect(resolved).to eq("sqlite3" => "1.6.9")
  end

  it "resolves RubyGems version metadata through a cacheable Kettle/Jem resolver" do
    response = Struct.new(:code, :body)
    calls = []
    http_get = lambda do |uri|
      calls << uri.to_s
      case uri.to_s
      when "https://example.test/api/v1/versions/active+record.json"
        response.new("200", JSON.dump([
          {"number" => "7.1.0.beta1", "ruby_version" => ">= 3.0", "prerelease" => true, "created_at" => "2024-01-01"},
          {"number" => "6.1.7", "ruby_version" => ">= 2.5", "prerelease" => false, "created_at" => "2023-01-01"},
          {"number" => "7.1.3", "ruby_version" => ">= 2.7", "prerelease" => false, "created_at" => "2024-02-01"}
        ]))
      when "https://example.test/api/v2/rubygems/active+record/versions/7.1.3.json"
        response.new("200", JSON.dump({
          "number" => "7.1.3",
          "ruby_version" => ">= 2.7",
          "dependencies" => {
            "runtime" => [
              {"name" => "sqlite3", "requirements" => "~> 1.6"}
            ]
          }
        }))
      else
        response.new("404", "{}")
      end
    end

    resolver = described_class::RubyGemsResolver.new(
      http_get: http_get,
      v1_api_base: "https://example.test/api/v1",
      v2_api_base: "https://example.test/api/v2/rubygems"
    )

    expect(resolver.versions("active record", requirements: ">= 7.0")).to eq(
      [
        {number: "7.1.3", ruby_version: ">= 2.7", created_at: "2024-02-01", prerelease: false}
      ]
    )
    expect(resolver.versions("active record", include_prerelease: true).map { |entry| entry.fetch(:number) }).to eq(
      ["6.1.7", "7.1.0.beta1", "7.1.3"]
    )
    expect(resolver.min_ruby_version("active record", "7.1.3")).to eq(Gem::Version.new("2.7"))
    expect(resolver.minor_versions_by_major("active record")).to eq(
      [
        {major: 6, minors: ["6.1"]},
        {major: 7, minors: ["7.1"]}
      ]
    )
    expect(resolver.version_info("active record", "7.1.3")).to eq(
      {
        number: "7.1.3",
        ruby_version: ">= 2.7",
        runtime_dependencies: [
          {name: "sqlite3", requirements: "~> 1.6"}
        ]
      }
    )
    expect(resolver.version_info("active record", "7.1.3")).to be_a(Hash)
    expect(calls.tally).to eq(
      "https://example.test/api/v1/versions/active+record.json" => 1,
      "https://example.test/api/v2/rubygems/active+record/versions/7.1.3.json" => 1
    )
  end

  it "loads gemspec metadata through Kettle/Jem GemSpecReader" do
    Dir.mktmpdir do |project_root|
      write_tree(
        project_root,
        {
          "demo_tool.gemspec" => <<~RUBY,
            Gem::Specification.new do |spec|
              spec.name = "demo_tool"
              spec.version = "0.1.0"
              spec.authors = ["Demo Author"]
              spec.email = ["demo@example.com"]
              spec.summary = "Demo"
              spec.homepage = "https://github.com/example/demo_tool"
              spec.required_ruby_version = ">= 3.2"
              spec.add_dependency "runtime_dep", ">= 1"
              spec.add_development_dependency "dev_dep", ">= 1"
            end
          RUBY
          "lib/demo_tool/version.rb" => "module DemoTool; VERSION = '0.1.0'; end\n"
        }
      )

      described_class::GemSpecReader.clear_cache!

      metadata = described_class::GemSpecReader.load(project_root)

      expect(metadata).to include(
        gem_name: "demo_tool",
        version: "0.1.0",
        min_ruby: Gem::Version.new("3.2"),
        homepage: "https://github.com/example/demo_tool",
        gh_org: "example",
        gh_repo: "demo_tool",
        namespace: "DemoTool",
        entrypoint_require: "demo_tool"
      )
      expect(metadata.fetch(:runtime_dependencies).map(&:name)).to eq(["runtime_dep"])
      expect(metadata.fetch(:development_dependencies).map(&:name)).to eq(["dev_dep"])
    end
  ensure
    described_class::GemSpecReader.clear_cache!
  end

  it "ports appraisal CLI config orchestration helpers into Kettle/Jem" do
    gemspec_content = <<~RUBY
      Gem::Specification.new do |spec|
        spec.add_dependency "activerecord", "~> 7.1"
        spec.add_runtime_dependency("erb", ">= 0")
        # spec.add_dependency "ignored"
        spec.add_runtime_dependency "sequel", ">= 5.0"
        spec.add_development_dependency "dev_only", ">= 0"
      end
    RUBY

    scaffold = described_class.appraisal_scaffold_config(
      gemspec_content: gemspec_content,
      existing_config: {
        appraisal_matrix: {
          gems: {
            tier2: [
              {name: "omniauth"}
            ]
          }
        }
      },
      exclusions: ["erb"],
      freshness_ttl: 86_400
    )

    expect(scaffold.fetch("appraisal_matrix")).to include(
      "mode" => "semver",
      "freshness_ttl" => 86_400
    )
    expect(scaffold.dig("appraisal_matrix", "gems", "tier1")).to eq(
      [
        {"name" => "activerecord"},
        {"name" => "sequel"}
      ]
    )
    expect(scaffold.dig("appraisal_matrix", "gems", "tier2")).to eq([{"name" => "omniauth"}])

    expect(described_class.appraisal_matrix_has_versions?(
      "gems" => {
        "tier1" => [{"name" => "activerecord", "versions" => []}],
        "tier2" => [{"name" => "omniauth", "versions" => ["2.1"]}]
      }
    )).to be true
    expect(described_class.appraisal_matrix_fresh?({"resolved_at" => 100, "freshness_ttl" => 50}, now: 149)).to be true
    expect(described_class.appraisal_matrix_fresh?({"resolved_at" => 100, "freshness_ttl" => 50}, now: 150)).to be false
    expect(described_class.appraisal_time_ago(0, now: 90_000)).to eq("1d")
    expect(described_class.appraisal_finalize_versions(%w[7.1.0 7.1.1], include_versions: ["6.0.9"], exclude_versions: ["7.1.0"])).to eq(
      %w[6.0.9 7.1.1]
    )

    resolver = Class.new do
      def versions(gem_name, requirements: nil)
        case [gem_name, requirements]
        when ["activerecord", [">= 7.1", "< 7.2"]]
          [{number: "7.1.0"}, {number: "7.1.1"}]
        when ["omniauth", nil]
          [{number: "2.0.0"}, {number: "2.1.3"}]
        else
          []
        end
      end

      def minor_versions_by_major(gem_name, requirements: nil)
        case [gem_name, requirements]
        when ["sequel", nil]
          [{major: 5, minors: ["5.0", "5.9"]}]
        else
          []
        end
      end

      def min_ruby_version(gem_name, version)
        return Gem::Version.new("3.2") if gem_name == "omniauth" && version == "2.1.3"

        Gem::Version.new("2.7")
      end
    end.new

    expect(described_class.appraisal_all_versions_for(
      resolver: resolver,
      gem_name: "activerecord",
      mode: "patch",
      requirements: [">= 7.1", "< 7.2"],
      include_versions: ["6.0.9"],
      exclude_versions: ["7.1.0"]
    )).to eq(%w[6.0.9 7.1.1])
    expect(described_class.appraisal_all_versions_for(resolver: resolver, gem_name: "sequel", mode: "major")).to eq(%w[5.0 5.9])
    expect(described_class.appraisal_compatible_version_for_bucket?(
      resolver: resolver,
      gem_name: "omniauth",
      version: "2.1",
      ruby_series: "r3.1",
      bucket_ranges: {"r3.1" => {floor: "3.0", ceiling: "3.1"}}
    )).to be false
  end

  it "plans stale flat appraisal gemfile cleanup paths" do
    stale_paths = described_class.appraisal_stale_gemfile_paths(
      existing_paths: [
        "gemfiles/kja-ar-7-1-r3.gemfile",
        "gemfiles/kja-ar-6-1-r2.gemfile",
        "gemfiles/manual.gemfile",
        "gemfiles/modular/activerecord/r3/v7.1.gemfile"
      ],
      current_entries: [
        {name: "kja-ar-7-1-r3"}
      ]
    )

    expect(stale_paths).to eq(["gemfiles/kja-ar-6-1-r2.gemfile"])
  end

  it "honors author template token config and environment overrides" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-author-token-override-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.authors = ["Jane Q Public"]
            spec.email = ["jane@example.test"]
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML,
          tokens:
            author:
              name: Config Person
              given_names: Config
              family_names: Person
              email: config@example.test
              domain: config.example.test
              orcid: "{KJ|AUTHOR:ORCID}"
          templates:
            root: template
            apply: true
            entries:
              - README.md
        YAML
        "template/README.md.example" => <<~MARKDOWN
          Author: {KJ|AUTHOR:NAME}
          Given: {KJ|AUTHOR:GIVEN_NAMES}
          Family: {KJ|AUTHOR:FAMILY_NAMES}
          Email: {KJ|AUTHOR:EMAIL}
          Domain: {KJ|AUTHOR:DOMAIN}
          ORCID: {KJ|AUTHOR:ORCID}
        MARKDOWN
      })

      plan = described_class.plan_project(
        root,
        env: {
          "KJ_AUTHOR_NAME" => "Env A Writer",
          "KJ_AUTHOR_EMAIL" => "env@example.test",
          "KJ_AUTHOR_DOMAIN" => "env.example.test",
          "KJ_AUTHOR_ORCID" => "0000-0002-1825-0097"
        }
      )
      template_report = plan[:recipe_reports].find do |report|
        report.fetch(:recipe_name) == "template_source_application_README_md"
      end
      expect(template_report.fetch(:final_content)).to eq(<<~MARKDOWN)
        Author: Env A Writer
        Given: Config
        Family: Person
        Email: env@example.test
        Domain: env.example.test
        ORCID: 0000-0002-1825-0097
      MARKDOWN
      expect(template_report.dig(:metadata, :template_tokens)).to include(
        "KJ|AUTHOR:DOMAIN" => "env.example.test",
        "KJ|AUTHOR:EMAIL" => "env@example.test",
        "KJ|AUTHOR:FAMILY_NAMES" => "Person",
        "KJ|AUTHOR:GIVEN_NAMES" => "Config",
        "KJ|AUTHOR:NAME" => "Env A Writer",
        "KJ|AUTHOR:ORCID" => "0000-0002-1825-0097"
      )
    end
  end

  it "applies author email environment overrides to gemspec and destination config" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-author-email-env-sync-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.authors = ["Jane Q Public"]
            spec.email = ["old@example.test"]
          end
        RUBY
        ".structuredmerge/kettle-jem.yml" => <<~YAML,
          tokens:
            author:
              name: Jane Q Public
              email: old@example.test
          templates:
            root: template
            apply: true
            entries:
              - .structuredmerge/kettle-jem.yml
              - source: gem.gemspec
                target: example.gemspec
        YAML
        "template/.structuredmerge/kettle-jem.yml.example" => <<~YAML,
          tokens:
            author:
              name: Jane Q Public
              email: old@example.test
          templates:
            root: template
            apply: true
            entries:
              - .structuredmerge/kettle-jem.yml
              - source: gem.gemspec
                target: example.gemspec
        YAML
        "template/gem.gemspec.example" => <<~RUBY
          Gem::Specification.new do |spec|
            spec.name = "{KJ|GEM_NAME}"
            spec.summary = "Example gem"
            spec.authors = ["{KJ|AUTHOR:NAME}"]
            spec.email = ["{KJ|AUTHOR:EMAIL}"]
          end
        RUBY
      })

      apply = described_class.apply_project(
        root,
        env: {"KJ_AUTHOR_EMAIL" => "env@example.test"},
        run_options: {accept: true}
      )
      gemspec_report = apply.fetch(:recipe_reports).find { |report| report.fetch(:relative_path) == "example.gemspec" }
      config_report = apply.fetch(:recipe_reports).find { |report| report.fetch(:relative_path) == ".structuredmerge/kettle-jem.yml" }

      expect(gemspec_report.fetch(:final_content)).to include('spec.email = ["env@example.test"]')
      expect(YAML.safe_load(config_report.fetch(:final_content)).dig("tokens", "author", "email")).to eq("env@example.test")
      expect(File.read(File.join(root, "example.gemspec"))).to include('spec.email = ["env@example.test"]')
      expect(YAML.safe_load_file(File.join(root, ".structuredmerge/kettle-jem.yml")).dig("tokens", "author", "email")).to eq("env@example.test")
    end
  end

  it "preserves existing multi-author gemspec metadata in packaged gemspec templates" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-gemspec-multi-authors-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.description = "Example gem"
            spec.authors = ["First Author", "Second Author"]
            spec.email = ["authors@example.test"]
            spec.metadata["source_code_uri"] = "https://github.com/acme/example"
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML
          templates:
            root: packaged
            apply: true
            entries:
              - source: gem.gemspec
                target: example.gemspec
        YAML
      })

      apply = described_class.apply_project(root, env: {}, run_options: {accept: true})
      gemspec_report = apply.fetch(:recipe_reports).find { |report| report.fetch(:relative_path) == "example.gemspec" }

      expect(gemspec_report.fetch(:final_content)).to include('spec.authors = ["First Author", "Second Author"]')
      expect(gemspec_report.dig(:metadata, :template_tokens)).to include(
        "KJ|AUTHOR:NAME" => "First Author",
        "KJ|AUTHOR:NAMES" => '["First Author", "Second Author"]'
      )
      expect(File.read(File.join(root, "example.gemspec"))).to include('spec.authors = ["First Author", "Second Author"]')
    end
  end

  it "derives author names from copyright holders when gemspec authors are absent" do
    author = described_class.send(
      :author_facts,
      {},
      {},
      copyright: {
        lines: [
          "Copyright (c) 2020 Ada Lovelace",
          "Copyright (c) 2021, 2023-2024 Grace Hopper"
        ]
      }
    )

    expect(described_class.send(:author_template_tokens, author)).to include(
      "KJ|AUTHOR:NAMES" => '["Ada Lovelace", "Grace Hopper"]'
    )
  end

  it "expands existing gemspec authors with copyright holders" do
    author = described_class.send(
      :author_facts,
      {},
      {},
      gemspec_metadata: {authors: ["Existing Author"]},
      copyright: {
        lines: [
          "Copyright (c) 2020 Ada Lovelace",
          "Copyright (c) 2021 Grace Hopper"
        ]
      }
    )

    expect(author.fetch(:names)).to eq(["Existing Author", "Ada Lovelace", "Grace Hopper"])
  end

  it "consolidates configured author aliases across gemspec and copyright metadata" do
    author = described_class.send(
      :author_facts,
      {
        "author_aliases" => {
          "A. Lovelace" => "Ada Lovelace",
          "ada.old@example.test" => "Ada Lovelace",
          "G. Hopper" => "Grace Hopper"
        }
      },
      {},
      gemspec_metadata: {authors: ["A. Lovelace", "Grace Hopper"]},
      copyright: {
        lines: [
          "Copyright (c) 2020 A. Lovelace",
          "Copyright (c) 2021 Ada Lovelace",
          "Copyright (c) 2022 G. Hopper"
        ]
      }
    )

    expect(author.fetch(:name)).to eq("Ada Lovelace")
    expect(author.fetch(:names)).to eq(["Ada Lovelace", "Grace Hopper"])
  end

  it "honors forge user template token config and environment overrides" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-forge-token-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML,
          tokens:
            forge:
              gh_user: config-gh
              gl_user: config-gl
              cb_user: "{KJ|CB:USER}"
              sh_user: config-sh
          templates:
            root: template
            apply: true
            entries:
              - README.md
        YAML
        "template/README.md.example" => <<~MARKDOWN
          GitHub: {KJ|GH:USER}
          GitLab: {KJ|GL:USER}
          Codeberg: {KJ|CB:USER}
          SourceHut: {KJ|SH:USER}
        MARKDOWN
      })

      plan = described_class.plan_project(
        root,
        env: {
          "KJ_GH_USER" => "env-gh",
          "KJ_CB_USER" => "env-cb"
        }
      )
      template_report = plan[:recipe_reports].find do |report|
        report.fetch(:recipe_name) == "template_source_application_README_md"
      end
      expect(template_report.fetch(:final_content)).to eq(<<~MARKDOWN)
        GitHub: env-gh
        GitLab: config-gl
        Codeberg: env-cb
        SourceHut: config-sh
      MARKDOWN
      expect(template_report.dig(:metadata, :template_tokens)).to include(
        "KJ|CB:USER" => "env-cb",
        "KJ|GH:USER" => "env-gh",
        "KJ|GL:USER" => "config-gl",
        "KJ|SH:USER" => "config-sh"
      )
    end
  end

  it "honors supported funding platform template token config and environment overrides" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-funding-token-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML,
          tokens:
            funding:
              kofi: config-kofi
              paypal: "{KJ|FUNDING:PAYPAL}"
              buymeacoffee: config-bmac
              liberapay: config-liberapay
          templates:
            root: template
            apply: true
            entries:
              - README.md
        YAML
        "template/README.md.example" => <<~MARKDOWN
          Ko-fi: {KJ|FUNDING:KOFI}
          PayPal: {KJ|FUNDING:PAYPAL}
          BuyMeACoffee: {KJ|FUNDING:BUYMEACOFFEE}
          Liberapay: {KJ|FUNDING:LIBERAPAY}
        MARKDOWN
      })

      plan = described_class.plan_project(
        root,
        env: {
          "KJ_FUNDING_PAYPAL" => "env-paypal"
        }
      )
      template_report = plan[:recipe_reports].find do |report|
        report.fetch(:recipe_name) == "template_source_application_README_md"
      end
      expect(template_report.fetch(:final_content)).to eq(<<~MARKDOWN)
        Ko-fi: config-kofi
        PayPal: env-paypal
        BuyMeACoffee: config-bmac
        Liberapay: config-liberapay
      MARKDOWN
      expect(template_report.dig(:metadata, :template_tokens)).to include(
        "KJ|FUNDING:BUYMEACOFFEE" => "config-bmac",
        "KJ|FUNDING:KOFI" => "config-kofi",
        "KJ|FUNDING:LIBERAPAY" => "config-liberapay",
        "KJ|FUNDING:PAYPAL" => "env-paypal"
      )
    end
  end

  it "normalizes SECURITY.md supported version token from the gem version" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)

    {
      "0.2.0" => "0.latest",
      "2.5.7" => "2.5.latest"
    }.each do |gem_version, supported_version|
      Dir.mktmpdir("kettle-jem-security-version-token-slice", tmp_root) do |root|
        write_tree(root, {
          "example.gemspec" => <<~RUBY,
            Gem::Specification.new do |spec|
              spec.name = "example"
              spec.summary = "Example gem"
              spec.version = "#{gem_version}"
            end
          RUBY
          ".kettle-jem.yml" => <<~YAML,
            templates:
              root: template
              apply: true
              entries:
                - SECURITY.md
          YAML
          "template/SECURITY.md.example" => <<~MARKDOWN
            | Version  | Supported |
            |----------|-----------|
            | {KJ|SECURITY:SUPPORTED_VERSION} | ✅         |
          MARKDOWN
        })

        plan = described_class.plan_project(root, env: {})
        template_report = plan[:recipe_reports].find do |report|
          report.fetch(:recipe_name).start_with?("template_source_") &&
            report.fetch(:recipe_name).end_with?("_SECURITY_md")
        end
        expect(template_report.fetch(:final_content)).to include("| #{supported_version} | ✅")
        expect(template_report.dig(:metadata, :template_tokens)).to include(
          "KJ|SECURITY:SUPPORTED_VERSION" => supported_version
        )
      end
    end
  end

  it "honors social template token config and environment overrides" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-social-token-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML,
          tokens:
            social:
              mastodon: config-mastodon
              bluesky: config-bluesky
              linktree: "{KJ|SOCIAL:LINKTREE}"
              devto: config-devto
          templates:
            root: template
            apply: true
            entries:
              - README.md
        YAML
        "template/README.md.example" => <<~MARKDOWN
          Mastodon: {KJ|SOCIAL:MASTODON}
          Bluesky: {KJ|SOCIAL:BLUESKY}
          Linktree: {KJ|SOCIAL:LINKTREE}
          Dev.to: {KJ|SOCIAL:DEVTO}
        MARKDOWN
      })

      plan = described_class.plan_project(
        root,
        env: {
          "KJ_SOCIAL_MASTODON" => "env-mastodon",
          "KJ_SOCIAL_LINKTREE" => "env-linktree"
        }
      )
      template_report = plan[:recipe_reports].find do |report|
        report.fetch(:recipe_name) == "template_source_application_README_md"
      end
      expect(template_report.fetch(:final_content)).to eq(<<~MARKDOWN)
        Mastodon: env-mastodon
        Bluesky: config-bluesky
        Linktree: env-linktree
        Dev.to: config-devto
      MARKDOWN
      expect(template_report.dig(:metadata, :template_tokens)).to include(
        "KJ|SOCIAL:BLUESKY" => "config-bluesky",
        "KJ|SOCIAL:DEVTO" => "config-devto",
        "KJ|SOCIAL:LINKTREE" => "env-linktree",
        "KJ|SOCIAL:MASTODON" => "env-mastodon"
      )
    end
  end

  it "projects license template tokens from configured licenses" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-license-token-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.authors = ["Jane Q Public"]
            spec.email = ["jane@example.test"]
            spec.metadata["source_code_uri"] = "https://github.com/acme/example"
            spec.licenses = ["MIT"]
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML
          licenses:
            - AGPL-3.0-only
            - PolyForm-Small-Business-1.0.0
            - LicenseRef-Big-Time-Public-License
          readme:
            package_family: structuredmerge
          templates:
            root: packaged
            apply: true
            entries:
              - LICENSE.md
        YAML
      })

      plan = described_class.plan_project(root, env: {})
      template_report = plan[:recipe_reports].find do |report|
        report.fetch(:recipe_name) == "template_source_application_LICENSE_md"
      end
      final_content = template_report.fetch(:final_content)
      expect(plan.dig(:facts, :license, :spdx)).to eq(
        ["AGPL-3.0-only", "PolyForm-Small-Business-1.0.0", "LicenseRef-Big-Time-Public-License"]
      )
      expect(plan.dig(:facts, :package, :license_expression)).to eq(
        "AGPL-3.0-only OR PolyForm-Small-Business-1.0.0 OR LicenseRef-Big-Time-Public-License"
      )
      expect(final_content).to include("[AGPL-3.0-only](https://github.com/acme/example/blob/main/AGPL-3.0-only.md)")
      expect(final_content).to include("[PolyForm-Small-Business-1.0.0](https://github.com/acme/example/blob/main/PolyForm-Small-Business-1.0.0.md)")
      expect(final_content).to include("[Big-Time-Public-License](https://github.com/acme/example/blob/main/Big-Time-Public-License.md)")
      expect(final_content).to include("## Use-case guide")
      expect(final_content).to include("- Required Notice: Copyright")
      expect(final_content).to include("Jane Q Public")
      expect(template_report.dig(:metadata, :template_tokens)).to include(
        "KJ|COPYRIGHT_PREFIX" => "Required Notice: ",
        "KJ|LICENSE:PRIMARY_SPDX" => "AGPL-3.0-only",
        "KJ|LICENSE_EYE:PRIMARY_SPDX" => "AGPL-3.0-only",
        "KJ|LICENSE_EYE:MODE" => "resolve",
        "KJ|LICENSE_EYE:FLAGS" => ""
      )
      expect(template_report.dig(:metadata, :template_tokens, "KJ|LICENSE_MD_CONTENT")).to include(
        "This project is made available under the following licenses."
      )
      expect(template_report.dig(:metadata, :template_tokens, "KJ|README:LICENSE_BADGE")).to eq(
        "[![License: AGPL-3.0-only OR PolyForm-Small-Business-1.0.0 OR LicenseRef-Big-Time-Public-License][📄license-img]][📄license]"
      )
      expect(template_report.dig(:metadata, :template_tokens, "KJ|README:LICENSE_REFS")).to include(
        "[📄license-ref]: LICENSE.md"
      )
      expect(template_report.dig(:metadata, :template_tokens, "KJ|README:LICENSE_REFS")).to include(
        "License-AGPL--3.0--only_OR_PolyForm--Small--Business--1.0.0_OR_LicenseRef--Big--Time--Public--License"
      )
      expect(template_report.dig(:metadata, :template_tokens, "KJ|README:FAMILY_INTRO_BACKEND_MATRIX")).to include(
        "https://github.com/structuredmerge/structuredmerge-ruby#package-family"
      )
      expect(template_report.dig(:metadata, :template_tokens, "KJ|README:FAMILY_INTRO_BACKEND_MATRIX")).to include(
        "StructuredMerge Ruby package family"
      )
      expect(template_report.dig(:metadata, :template_tokens, "KJ|README:FAMILY_INTRO_BACKEND_MATRIX")).to include(
        "Merge analysis must enter parsing through `tree_haver`"
      )
    end
  end

  it "uses MIT as the License-Eye compatibility license when MIT is configured" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-license-eye-token-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.authors = ["Jane Q Public"]
            spec.email = ["jane@example.test"]
            spec.licenses = ["AGPL-3.0-only"]
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML
          licenses:
            - AGPL-3.0-only
            - MIT
          license_eye:
            dependency_licenses:
              - name: simplecov-rcov
                version: 0.3.7
                license: MIT
          templates:
            root: packaged
            apply: true
            entries:
              - .licenserc.yaml
              - .github/workflows/license-eye.yml
        YAML
      })

      plan = described_class.plan_project(root, env: {})
      licenserc_report = plan[:recipe_reports].find do |report|
        report.fetch(:relative_path) == ".licenserc.yaml"
      end
      workflow_report = plan[:recipe_reports].find do |report|
        report.fetch(:relative_path) == ".github/workflows/license-eye.yml"
      end

      expect(licenserc_report.fetch(:final_content)).to include('spdx-id: "MIT"')
      expect(licenserc_report.fetch(:final_content)).to include("  licenses:\n    - name: \"simplecov-rcov\"\n      version: \"0.3.7\"\n      license: \"MIT\"")
      expect(workflow_report.fetch(:final_content)).to include('mode: "check"')
      expect(workflow_report.fetch(:final_content)).to include('flags: "--weak-compatible"')
    end
  end

  it "formats README metadata SPDX license identifiers as code spans" do
    block = described_class.readme_metadata_block(
      package: {
        name: "example",
        description: "Example gem",
        homepage_url: "https://example.test",
        source_url: "https://example.test/source",
        license_expression: "AGPL-3.0-only OR PolyForm-Small-Business-1.0.0"
      },
      license: {
        spdx: ["AGPL-3.0-only", "PolyForm-Small-Business-1.0.0"]
      },
      funding: {
        urls: []
      }
    )

    expect(block).to include("| License | `AGPL-3.0-only` OR `PolyForm-Small-Business-1.0.0` |")
  end

  it "formats README metadata values as Markdown table cells" do
    block = described_class.readme_metadata_block(
      package: {
        name: "example",
        description: "First line\n  Second | line\r\nThird line",
        homepage_url: "https://example.test",
        source_url: "https://example.test/source",
        license_expression: "MIT"
      },
      license: {
        spdx: ["MIT"]
      },
      funding: {
        urls: []
      }
    )

    expect(block).to include("| Description | First line<br>Second \\| line<br>Third line |")
    expect(block).not_to include("First line\n")
  end

  it "renders optional FOSSA README badge tokens from configuration" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-fossa-readme-badge", tmp_root) do |root|
      disabled_style = described_class.readme_style_facts(
        root,
        {"readme" => {"badges" => {"fossa" => false}}},
        {spdx: ["MIT"]},
        repository: {slug: "galtzo-floss/example"}
      )
      enabled_style = described_class.readme_style_facts(
        root,
        {"readme" => {"badges" => {"fossa" => "git+github.com/pboling/flag_shih_tzu"}}},
        {spdx: ["MIT"]},
        repository: {slug: "galtzo-floss/flag_shih_tzu"}
      )

      expect(disabled_style[:fossa_project]).to be_nil
      tokens = described_class.readme_fossa_template_tokens(enabled_style)
      expect(tokens.fetch("KJ|README:FOSSA_BADGE")).to eq("[![FOSSA Status][🧪fossa-img]][🧪fossa]")
      expect(tokens.fetch("KJ|README:FOSSA_REFS")).to include("git%2Bgithub.com%2Fpboling%2Fflag_shih_tzu.svg?type=shield")
      expect(tokens.fetch("KJ|README:FOSSA_REFS")).to include("git%2Bgithub.com%2Fpboling%2Fflag_shih_tzu?ref=badge_shield")
    end
  end

  it "disables coverage integrations across README badges, upload steps, templates, and config cleanup" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-disabled-coverage-integrations", tmp_root) do |root|
      FileUtils.mkdir_p(File.join(root, ".github"))
      FileUtils.mkdir_p(File.join(root, ".qlty"))
      File.write(File.join(root, ".github/.codecov.yml"), "codecov:\n")
      File.write(File.join(root, ".coveralls.yml"), "service_name: github\n")
      File.write(File.join(root, ".qlty/qlty.toml"), "# qlty\n")

      config = {
        "integrations" => {
          "qlty" => false,
          "disabled" => %w[codecov coveralls]
        },
        "templates" => {
          "root" => "packaged",
          "apply" => true
        }
      }

      readme_style = described_class.readme_style_facts(
        root,
        config,
        {spdx: ["MIT"]},
        repository: {slug: "omniauth/omniauth-jwt2"}
      )
      expect(readme_style.fetch(:disabled_integrations)).to contain_exactly("codecov", "coveralls", "qlty")

      upload_steps = described_class.github_actions_coverage_steps(disabled_integrations: readme_style.fetch(:disabled_integrations))
      expect(upload_steps).not_to include("Upload coverage to Coveralls")
      expect(upload_steps).not_to include("Upload coverage to QLTY")
      expect(upload_steps).not_to include("Upload coverage to CodeCov")
      expect(upload_steps).to include("Code Coverage Summary Report")

      template_paths = described_class.template_source_preferences(root, config).map { |preference| preference.fetch(:target_path) }
      expect(template_paths).not_to include(".github/.codecov.yml", ".qlty/qlty.toml")

      cleanup_paths = described_class.inactive_packaged_template_cleanup_files(root, config).map { |cleanup| cleanup.fetch(:target_path) }
      expect(cleanup_paths).to include(".github/.codecov.yml", ".coveralls.yml", ".qlty/qlty.toml")
    end
  end

  it "keeps coverage integrations active when only README badges are disabled" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-readme-only-coverage-badge-disable", tmp_root) do |root|
      config = {
        "readme" => {
          "badges" => {
            "disabled" => %w[qlty]
          }
        },
        "templates" => {
          "root" => "packaged",
          "apply" => true
        }
      }

      expect(described_class.disabled_coverage_integrations(config)).to be_empty

      readme_style = described_class.readme_style_facts(
        root,
        config,
        {spdx: ["MIT"]},
        repository: {slug: "omniauth/omniauth-jwt2"}
      )
      expect(readme_style.fetch(:disabled_integrations)).to contain_exactly("qlty")

      upload_steps = described_class.github_actions_coverage_steps(disabled_integrations: described_class.disabled_coverage_integrations(config))
      expect(upload_steps).to include("Upload coverage to Coveralls")
      expect(upload_steps).to include("Upload coverage to QLTY")
      expect(upload_steps).to include("Upload coverage to CodeCov")
      expect(upload_steps).to include("fail-on-error: false")
      expect(upload_steps).to include("skip-errors: true")
      expect(upload_steps.scan("continue-on-error: true").length).to be >= 3

      template_paths = described_class.template_source_preferences(root, config).map { |preference| preference.fetch(:target_path) }
      expect(template_paths).to include(".github/.codecov.yml", ".qlty/qlty.toml")
      expect(described_class.inactive_packaged_template_cleanup_files(root, config)).to be_empty
    end
  end

  it "supports partial coverage integration disablement" do
    config = {
      "integrations" => {
        "code_cov" => false,
        "qlty" => true,
        "coveralls" => "false"
      }
    }

    expect(described_class.disabled_coverage_integrations(config)).to contain_exactly("codecov", "coveralls")

    upload_steps = described_class.github_actions_coverage_steps(disabled_integrations: described_class.disabled_coverage_integrations(config))
    expect(upload_steps).not_to include("Upload coverage to Coveralls")
    expect(upload_steps).not_to include("Upload coverage to CodeCov")
    expect(upload_steps).to include("Upload coverage to QLTY")

    workflow = <<~YAML
      jobs:
        coverage:
          steps:
            - name: Existing
              run: true
    YAML
    updated = described_class.append_github_actions_coverage_steps(workflow, disabled_integrations: described_class.disabled_coverage_integrations(config))
    expect(updated).to include("Upload coverage to QLTY")
    expect(updated).not_to include("Upload coverage to Coveralls")
    expect(described_class.append_github_actions_coverage_steps(updated, disabled_integrations: [])).to eq(updated)

    workflow_without_steps = <<~YAML
      jobs:
        coverage:
          runs-on: ubuntu-latest
    YAML
    expect(described_class.append_github_actions_coverage_steps(workflow_without_steps, disabled_integrations: [])).to eq(workflow_without_steps)
  end

  it "disables SkyWalking Eyes from boolean keys and disabled lists" do
    expect(described_class.disabled_integrations(
      {
        "integrations" => {
          "skywalking_eyes" => false
        }
      },
      license: {spdx: ["MIT"]}
    )).to include("skywalking-eyes")

    expect(described_class.disabled_integrations(
      {
        "integrations" => {
          "disabled" => %w[license-eye]
        }
      },
      license: {spdx: ["MIT"]}
    )).to include("skywalking-eyes")
  end

  it "defaults SkyWalking Eyes off unless a compatible license is configured" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-skywalking-eyes-default-disable", tmp_root) do |root|
      FileUtils.mkdir_p(File.join(root, ".github/workflows"))
      File.write(File.join(root, ".licenserc.yaml"), "dependency:\n")
      File.write(File.join(root, ".github/workflows/license-eye.yml"), "name: Apache SkyWalking Eyes\n")
      config = {
        "licenses" => %w[AGPL-3.0-only],
        "templates" => {
          "root" => "packaged",
          "apply" => true
        }
      }
      license = {spdx: ["AGPL-3.0-only"]}
      template_config = described_class.template_runtime_config(config, {}, license: license)

      expect(described_class.disabled_integrations(config, license: license)).to include("skywalking-eyes")

      readme_style = described_class.readme_style_facts(
        root,
        config,
        license,
        repository: {slug: "example/example"}
      )
      expect(readme_style.fetch(:disabled_integrations)).to include("skywalking-eyes")

      template_paths = described_class.template_source_preferences(root, template_config).map { |preference| preference.fetch(:target_path) }
      expect(template_paths).not_to include(".licenserc.yaml", ".github/workflows/license-eye.yml")

      cleanup_paths = described_class.inactive_packaged_template_cleanup_files(root, template_config).map { |cleanup| cleanup.fetch(:target_path) }
      expect(cleanup_paths).to include(".licenserc.yaml")

      workflow_cleanup_paths = described_class.inactive_packaged_workflow_cleanup_files(root, template_config)
      expect(workflow_cleanup_paths).to include(".github/workflows/license-eye.yml")
    end
  end

  it "keeps SkyWalking Eyes enabled for MIT licenses and explicit opt-in" do
    mit_config = {
      "templates" => {
        "root" => "packaged",
        "apply" => true
      }
    }
    non_mit_opt_in_config = {
      "licenses" => %w[AGPL-3.0-only],
      "integrations" => {
        "skywalking-eyes" => true
      },
      "templates" => {
        "root" => "packaged",
        "apply" => true
      }
    }

    expect(described_class.disabled_integrations(mit_config, license: {spdx: ["MIT"]})).not_to include("skywalking-eyes")
    expect(described_class.disabled_integrations(non_mit_opt_in_config, license: {spdx: ["AGPL-3.0-only"]})).not_to include("skywalking-eyes")
    expect(described_class.license_eye_workflow_badge(["AGPL-3.0-only"], non_mit_opt_in_config)).to include(
      "Apache SkyWalking Eyes License Compatibility Check"
    )
  end

  it "applies configured licenses to merged gemspec output" do
    template = <<~RUBY
      Gem::Specification.new do |spec|
        spec.name = "example"
        spec.homepage = "https://example.test"
        spec.licenses = ["MIT"]
      end
    RUBY
    destination = <<~RUBY
      Gem::Specification.new do |spec|
        spec.name = "example"
        spec.homepage = "https://example.test"
        spec.licenses = ["AGPL-3.0-only"]
      end
    RUBY
    facts = {
      package: {name: "example"},
      license: {spdx: ["AGPL-3.0-only", "PolyForm-Small-Business-1.0.0"]}
    }

    output = described_class.merge_gemspec_template_source(template, destination, facts: facts)

    expect(output).to include('spec.licenses = ["AGPL-3.0-only", "PolyForm-Small-Business-1.0.0"]')
  end

  it "escapes and de-duplicates emoji in gemspec summary and description tokens" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-gemspec-description-token", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "🔍️ Find out what your Ruby gems are worth"
            spec.description = '🔍️ Example uses repeatable scenarios called "appraisals."'
            spec.homepage = "https://github.com/example/example"
            spec.required_ruby_version = ">= 2.3.0"
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML,
          project_emoji: 🔍️
          files:
            example.gemspec:
              strategy: accept_template
          templates:
            root: template
            apply: true
            entries:
              - example.gemspec
        YAML
        "template/example.gemspec.example" => <<~RUBY
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "{KJ|PROJECT_EMOJI} {KJ|GEMSPEC_PACKAGE_SUMMARY}"
            spec.description = "{KJ|PROJECT_EMOJI} {KJ|GEMSPEC_PACKAGE_DESCRIPTION}"
            spec.homepage = "https://github.com/example/example"
          end
        RUBY
      })

      described_class.apply_project(root, env: {})
      gemspec_path = File.join(root, "example.gemspec")
      gemspec = File.read(gemspec_path)

      expect(gemspec).to include('spec.summary = "🔍️ Find out what your Ruby gems are worth"')
      expect(gemspec).to include('spec.description = "🔍️ Example uses repeatable scenarios called \"appraisals.\""')
      expect(gemspec).not_to include("🔍️ 🔍️")
      expect(Gem::Specification.load(gemspec_path)).not_to be_nil
    end
  end

  it "refreshes README metadata during template-source README application" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-readme-metadata-order", tmp_root) do |root|
      metadata_block = described_class.readme_metadata_block(
        package: {
          name: "example",
          description: "Example gem",
          homepage_url: "https://example.test",
          source_url: "https://github.com/structuredmerge/structuredmerge-ruby",
          license_expression: "MIT"
        },
        license: {spdx: ["MIT"]},
        funding: {urls: ["https://tidelift.com/funding/github/rubygems/example"]}
      )
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.homepage = "https://example.test"
            spec.metadata["source_code_uri"] = "https://github.com/acme/example/tree/v1.2.3"
            spec.license = "MIT"
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML,
          templates:
            root: template
            apply: true
            entries:
              - README.md
        YAML
        "README.md" => <<~MARKDOWN,
          # Example

          Destination body.

          #{metadata_block}
        MARKDOWN
        "template/README.md.example" => "# {KJ|NAMESPACE}\n\nTemplate body.\n"
      })

      described_class.apply_project(root, env: {}, run_options: {accept: true, force: true})
      first_readme = File.read(File.join(root, "README.md"))
      described_class.apply_project(root, env: {}, run_options: {accept: true, force: true})

      expect(first_readme).to include("<!-- kettle-jem:metadata:start -->")
      expect(first_readme).to include("| Package | example |")
      expect(first_readme).to include("| Source | https://github.com/acme/example/tree/v1.2.3 |")
      expect(first_readme).not_to include("https://github.com/structuredmerge/structuredmerge-ruby")
      expect(File.read(File.join(root, "README.md"))).to eq(first_readme)
    end
  end

  it "applies and prunes root license files from configured licenses" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-license-file-prune-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.licenses = ["MIT"]
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML,
          licenses:
            - AGPL-3.0-only
            - PolyForm-Small-Business-1.0.0
          templates:
            root: packaged
            apply: true
            entries:
              - LICENSE.md
              - AGPL-3.0-only.md
              - MIT.md
              - PolyForm-Noncommercial-1.0.0.md
              - PolyForm-Small-Business-1.0.0.md
              - Big-Time-Public-License.md
        YAML
        "MIT.md" => "obsolete MIT license\n",
        "PolyForm-Noncommercial-1.0.0.md" => "obsolete PolyForm NC license\n",
        "Big-Time-Public-License.md" => "obsolete Big Time license\n"
      })

      apply = described_class.apply_project(root, env: {})
      recipe_names = apply[:recipe_reports].map { |report| report.fetch(:recipe_name) }

      expect(apply.dig(:facts, :license, :spdx)).to eq(["AGPL-3.0-only", "PolyForm-Small-Business-1.0.0"])
      expect(recipe_names).to include("template_source_application_AGPL_3_0_only_md")
      expect(recipe_names).to include("template_source_application_PolyForm_Small_Business_1_0_0_md")
      expect(recipe_names).not_to include("template_source_application_MIT_md")
      expect(recipe_names).not_to include("template_source_application_PolyForm_Noncommercial_1_0_0_md")
      expect(recipe_names).not_to include("template_source_application_Big_Time_Public_License_md")
      expect(apply[:changed_files]).to include(
        "MIT.md",
        "PolyForm-Noncommercial-1.0.0.md",
        "Big-Time-Public-License.md",
        "AGPL-3.0-only.md",
        "PolyForm-Small-Business-1.0.0.md"
      )
      expect(File).to exist(File.join(root, "AGPL-3.0-only.md"))
      expect(File).to exist(File.join(root, "PolyForm-Small-Business-1.0.0.md"))
      expect(File).not_to exist(File.join(root, "MIT.md"))
      expect(File).not_to exist(File.join(root, "PolyForm-Noncommercial-1.0.0.md"))
      expect(File).not_to exist(File.join(root, "Big-Time-Public-License.md"))
    end
  end

  it "does not package configured named license files in the generated gemspec by default" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-configured-license-entry-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.authors = ["Jane Q Public"]
            spec.email = ["jane@example.test"]
            spec.licenses = ["MIT"]
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML
          licenses:
            - MIT
          tokens:
            author:
              orcid: "0000-0000-0000-0000"
          templates:
            root: packaged
            apply: true
        YAML
      })

      apply = described_class.apply_project(root, env: {})
      recipe_names = apply[:recipe_reports].map { |report| report.fetch(:recipe_name) }

      expect(recipe_names).to include("template_source_application_example_gemspec")
      expect(apply[:changed_files]).to include("example.gemspec")
      gemspec = File.read(File.join(root, "example.gemspec"))
      expect(gemspec).to include("LICENSE.md")
      expect(gemspec).not_to include("MIT.md")
    end
  end

  it "renders configured extra package files in the generated gemspec" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-configured-package-files-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.authors = ["Jane Q Public"]
            spec.email = ["jane@example.test"]
            spec.licenses = ["MIT"]
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML
          gemspec:
            package_files:
              include:
                - data/**/*.json
                - config/runtime.yml
          tokens:
            author:
              orcid: "0000-0000-0000-0000"
          templates:
            root: packaged
            apply: true
        YAML
      })

      apply = described_class.apply_project(root, env: {})
      gemspec = File.read(File.join(root, "example.gemspec"))

      expect(apply.dig(:facts, :gemspec, :package_file_includes)).to eq(["data/**/*.json", "config/runtime.yml"])
      expect(gemspec).to include("# Extra package files configured by .structuredmerge/kettle-jem.yml")
      expect(gemspec).to include('*enumerate_package_glob.call(File.join(gemspec_root, "data/**/*.json"))')
      expect(gemspec).to include('*enumerate_package_glob.call(File.join(gemspec_root, "config/runtime.yml"))')
      expect(gemspec).to include("files = []")
      expect(gemspec).not_to include("filter_map")
      expect(gemspec).to include("relative_package_path.call(path)")
      expect { RubyVM::InstructionSequence.compile(gemspec) }.not_to raise_error
    end
  end

  it "does not package multiple configured named license files in the generated gemspec by default" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-configured-multi-license-entry-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.authors = ["Jane Q Public"]
            spec.email = ["jane@example.test"]
            spec.licenses = ["MIT"]
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML
          licenses:
            - AGPL-3.0-only
            - LicenseRef-Big-Time-Public-License
          tokens:
            author:
              orcid: "0000-0000-0000-0000"
          templates:
            root: packaged
            apply: true
        YAML
      })

      apply = described_class.apply_project(root, env: {})
      recipe_names = apply[:recipe_reports].map { |report| report.fetch(:recipe_name) }

      expect(recipe_names).to include("template_source_application_example_gemspec")
      expect(apply[:changed_files]).to include("example.gemspec")
      gemspec = File.read(File.join(root, "example.gemspec"))
      expect(gemspec).to include("LICENSE.md")
      expect(gemspec).not_to include("AGPL-3.0-only.md")
      expect(gemspec).not_to include("Big-Time-Public-License.md")
    end
  end

  it "projects copyright holders from git blame into license templates" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-copyright-slice", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.authors = ["Fallback Author"]
            spec.email = ["fallback@example.test"]
            spec.licenses = ["MIT"]
            spec.required_ruby_version = ">= 3.2"
          end
        RUBY
        "lib/example.rb" => <<~RUBY,
          module Example
            VERSION = "0.1.0"
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML,
          templates:
            root: templates
            apply: true
            entries:
              - LICENSE.md
              - README.md
        YAML
        "templates/LICENSE.md.example" => <<~MARKDOWN,
          {KJ|LICENSE_MD_CONTENT}

          {KJ|LICENSE_COPYRIGHT_NOTICE}
        MARKDOWN
        "templates/README.md.example" => <<~MARKDOWN,
          # 💎 Example

          ## 🌻 Synopsis

          Template synopsis.

          ## 📄 License

          {KJ|README:LICENSE_INTRO}

          ### © Copyright

          {KJ|README:COPYRIGHT_NOTICE}

          ## ⚙️ Configuration

          Template configuration.

          ## 🔧 Basic Usage

          Template usage.
        MARKDOWN
        "README.md" => <<~MARKDOWN
          # 💎 Example

          ## 🌻 Synopsis

          Project synopsis.

          ## ⚙️ Configuration

          Project configuration.

          ## 🔧 Basic Usage

          Project usage.
        MARKDOWN
      })
      expect(system("git", "-C", root, "init", "-q")).to be(true)
      expect(system("git", "-C", root, "config", "user.name", "Jane Contributor")).to be(true)
      expect(system("git", "-C", root, "config", "user.email", "jane@example.test")).to be(true)
      expect(system("git", "-C", root, "add", ".")).to be(true)
      commit_env = {
        "GIT_AUTHOR_NAME" => "Jane Contributor",
        "GIT_AUTHOR_EMAIL" => "jane@example.test",
        "GIT_AUTHOR_DATE" => "#{Time.now.utc.year}-01-02T00:00:00Z",
        "GIT_COMMITTER_NAME" => "Jane Contributor",
        "GIT_COMMITTER_EMAIL" => "jane@example.test",
        "GIT_COMMITTER_DATE" => "#{Time.now.utc.year}-01-02T00:00:00Z"
      }
      tree = IO.popen(["git", "-C", root, "write-tree"], &:read).strip
      commit = IO.popen(commit_env, ["git", "-C", root, "commit-tree", tree, "-m", "initial"], &:read).strip
      expect(commit).to match(/\A[0-9a-f]{40}\z/)
      expect(system("git", "-C", root, "update-ref", "refs/heads/main", commit)).to be(true)
      expect(system("git", "-C", root, "symbolic-ref", "HEAD", "refs/heads/main")).to be(true)

      plan = described_class.plan_project(root, env: {})
      license_report = plan[:recipe_reports].find { |report| report.fetch(:recipe_name) == "template_source_application_LICENSE_md" }
      readme_report = plan[:recipe_reports].find { |report| report.fetch(:recipe_name) == "template_source_application_README_md" }
      expected_line = "Copyright (c) #{Time.now.utc.year} Jane Contributor"
      expect(plan.dig(:facts, :copyright, :lines)).to eq([expected_line])
      expect(license_report.fetch(:final_content)).to include("## Copyright Notice")
      expect(license_report.fetch(:final_content)).to include("- #{expected_line}")
      expect(readme_report.fetch(:final_content)).to include("Copyright holders")
      expect(readme_report.fetch(:final_content)).to include("- #{expected_line}")
      expect(license_report.dig(:metadata, :template_tokens, "KJ|LICENSE_COPYRIGHT_NOTICE")).to include("- #{expected_line}")
    end
  end

  it "filters default machine users and consolidates Git author identities" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-copyright-identity-slice", tmp_root) do |root|
      expect(system("git", "-C", root, "init", "-q")).to be(true)
      expect(system("git", "-C", root, "config", "user.name", "Fixture User")).to be(true)
      expect(system("git", "-C", root, "config", "user.email", "fixture@example.test")).to be(true)

      commit = lambda do |name, email, path|
        File.write(File.join(root, path), "#{name}\n")
        expect(system("git", "-C", root, "add", path)).to be(true)
        commit_env = {
          "GIT_AUTHOR_NAME" => name,
          "GIT_AUTHOR_EMAIL" => email,
          "GIT_AUTHOR_DATE" => "2024-01-02T00:00:00Z",
          "GIT_COMMITTER_NAME" => name,
          "GIT_COMMITTER_EMAIL" => email,
          "GIT_COMMITTER_DATE" => "2024-01-02T00:00:00Z"
        }
        expect(system(commit_env, "git", "-C", root, "commit", "-qm", name)).to be(true)
      end

      commit.call("A. Lovelace", "ada.old@example.test", "first.txt")
      commit.call("Ada Lovelace", "ada@example.test", "second.txt")
      commit.call("autobolt", "automation@example.test", "automation.txt")

      facts = described_class.send(
        :copyright_facts,
        root,
        {
          "author_aliases" => {
            "A. Lovelace" => "Ada Lovelace",
            "ada.old@example.test" => "Ada Lovelace"
          }
        }
      )

      expect(described_class.send(:copyright_machine_users, {})).to eq(["autobolt"])
      expect(facts.fetch(:lines)).to eq(["Copyright (c) 2024 Ada Lovelace"])
    end
  end

  it "falls back to configured author copyright sections when git blame is unavailable" do
    tmp_root = File.expand_path("../tmp", __dir__)
    FileUtils.mkdir_p(tmp_root)
    Dir.mktmpdir("kettle-jem-copyright-author-fallback", tmp_root) do |root|
      write_tree(root, {
        "example.gemspec" => <<~RUBY,
          Gem::Specification.new do |spec|
            spec.name = "example"
            spec.summary = "Example gem"
            spec.authors = ["Peter H. Boling"]
            spec.email = ["floss@galtzo.com"]
            spec.licenses = ["AGPL-3.0-only"]
          end
        RUBY
        ".kettle-jem.yml" => <<~YAML,
          licenses:
            - AGPL-3.0-only
            - PolyForm-Small-Business-1.0.0
          tokens:
            author:
              given_names: Peter H.
              family_names: Boling
              email: floss@galtzo.com
          templates:
            root: template
            apply: true
            entries:
              - LICENSE.md
              - README.md
          files:
            README.md:
              strategy: accept_template
        YAML
        "README.md" => "# Example\n",
        "template/LICENSE.md.example" => "{KJ|LICENSE_MD_CONTENT}\n\n{KJ|LICENSE_COPYRIGHT_NOTICE}\n",
        "template/README.md.example" => "# Example\n\n## 📄 License\n\n{KJ|README:COPYRIGHT_NOTICE}\n"
      })

      plan = described_class.plan_project(root, env: {})
      license_report = plan[:recipe_reports].find { |report| report.fetch(:relative_path) == "LICENSE.md" }
      readme_report = plan[:recipe_reports].find { |report| report.fetch(:recipe_name) == "template_source_application_README_md" }
      expected_line = "Required Notice: Copyright (c) #{Time.now.utc.year} Peter H. Boling"

      expect(plan.fetch(:facts)).not_to have_key(:copyright)
      expect(license_report.fetch(:final_content)).to include("## Copyright Notice")
      expect(license_report.fetch(:final_content)).to include("- #{expected_line}")
      expect(readme_report.fetch(:final_content)).to include("Copyright holders")
      expect(readme_report.fetch(:final_content)).to include("- #{expected_line}")
    end
  end
end
