module Zip
  module Merge
    class Provider < Binary::Merge::Provider
      def provider_id: () -> String
      def family: () -> String
      def capabilities: () -> Hash[Symbol, untyped]
      def analyze: (Hash[Symbol, untyped] request) -> Hash[Symbol, untyped]
      def diff2: (Hash[Symbol, untyped] request) -> Hash[Symbol, untyped]
      def merge2: (Hash[Symbol, untyped] request) -> Hash[Symbol, untyped]
      def merge3: (Hash[Symbol, untyped] request) -> Hash[Symbol, untyped]
    end

    def self.merge_provider: () -> Provider
    def self.register_provider!: () -> Hash[Symbol, untyped]

    module Version
      VERSION: String
    end
    VERSION: String
  end
end
