source "https://rubygems.org"

gemspec path: "gems/tree_haver"
gemspec path: "gems/ast-merge"
gemspec path: "gems/ast-template"
gemspec path: "gems/text-merge"
gemspec path: "gems/json-merge"
gemspec path: "gems/toml-merge"
gemspec path: "gems/citrus-toml-merge"
gemspec path: "gems/parslet-toml-merge"
gemspec path: "gems/yaml-merge"
gemspec path: "gems/psych-merge"
gemspec path: "gems/markdown-merge"
gemspec path: "gems/kramdown-merge"
gemspec path: "gems/commonmarker-merge"
gemspec path: "gems/markly-merge"
gemspec path: "gems/ruby-merge"
gemspec path: "gems/prism-merge"
gemspec path: "gems/typescript-merge"
gemspec path: "gems/rust-merge"
gemspec path: "gems/go-merge"

gem "rake"
gem "rspec"
gem "token-resolver", "~> 1.0", ">= 1.0.2"
