#!/usr/bin/env ruby
# frozen_string_literal: true

script_basename = File.basename(__FILE__)
require_relative '../lib/smorg/rb/version'
if ARGV.any? { |arg| ['-v', '--version'].include?(arg) }
  puts Smorg::RB::Version::VERSION
  exit(0)
end

require 'smorg-rb'

puts "== #{script_basename} v#{Smorg::RB::Version::VERSION} ==" if ARGV.delete('--verbose')

exit(Smorg::RB.run(ARGV))
