# frozen_string_literal: true

require_relative "bootstrap/tree_haver_backends"
require_relative "bootstrap/merge_gems"

require_relative "../gems/ast-merge/spec/spec_helper"
require_relative "../gems/ast-merge-git/spec/spec_helper"
require_relative "../gems/ast-crispr/spec/spec_helper"
require_relative "../gems/ast-crispr-ruby-prism/spec/spec_helper"
require_relative "../gems/ast-crispr-markdown-markly/spec/spec_helper"
require_relative "../gems/ast-template/spec/spec_helper"
require_relative "../gems/kettle-jem/spec/spec_helper"
require_relative "../gems/tree_haver/spec/spec_helper"
require_relative "../gems/plain-merge/spec/spec_helper"
require_relative "../gems/bash-merge/spec/spec_helper"
require_relative "../gems/dotenv-merge/spec/spec_helper"
require_relative "../gems/rbs-merge/spec/spec_helper"
require_relative "../gems/binary-merge/spec/spec_helper"
require_relative "../gems/zip-merge/spec/spec_helper"
require_relative "../gems/json-merge/spec/spec_helper"
require_relative "../gems/toml-merge/spec/spec_helper"
require_relative "../gems/citrus-toml-merge/spec/spec_helper"
require_relative "../gems/parslet-toml-merge/spec/spec_helper"
require_relative "../gems/yaml-merge/spec/spec_helper"
require_relative "../gems/psych-merge/spec/spec_helper"
require_relative "../gems/markdown-merge/spec/spec_helper"
require_relative "../gems/kramdown-merge/spec/spec_helper"
require_relative "../gems/commonmarker-merge/spec/spec_helper"
require_relative "../gems/markly-merge/spec/spec_helper"
require_relative "../gems/ruby-merge/spec/spec_helper"
require_relative "../gems/prism-merge/spec/spec_helper"
require_relative "../gems/typescript-merge/spec/spec_helper"
require_relative "../gems/rust-merge/spec/spec_helper"
require_relative "../gems/go-merge/spec/spec_helper"
require_relative "../gems/smorg-rb/spec/spec_helper"

# Aggregate root specs load every subgem in one process, so shared contracts
# normally loaded by an individual subgem's focused specs must be registered here.
require "ast/crispr/rspec"
require "ast/merge/rspec/shared_examples"
require_relative "../gems/ast-merge/spec/support/fictive_language_harness"
require_relative "../gems/bash-merge/spec/support/shared_examples/file_analysis_examples"
require_relative "../gems/bash-merge/spec/support/shared_examples/smart_merger_examples"
