#!/usr/bin/env ruby
# frozen_string_literal: true

script_basename = File.basename(__FILE__)
repo_lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(repo_lib) if File.directory?(repo_lib) && !$LOAD_PATH.include?(repo_lib)

require "kettle/jem/version"

if ARGV.first == "version" || ARGV.any? { |arg| arg == "-v" || arg == "--version" }
  puts Kettle::Jem::Version::VERSION
  exit(0)
end

require "kettle-jem"

machine_output = ARGV.any? { |arg| arg == "--json" || arg.start_with?("--events") }
puts "== #{script_basename} v#{Kettle::Jem::Version::VERSION} ==" if ARGV.include?("--verbose") && !machine_output

exit(Kettle::Jem::CLI.run(ARGV, env: ENV, out: $stdout, err: $stderr))
