name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - "main"
      - "*-stable"
    tags:
      - "!*" # Do not execute on tags
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    name: Specs ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "4.0"
        rubygems:
          - default
        bundler:
          - default

    steps:
      - name: Checkout kettle-jem
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: "${{ matrix.ruby }}"
          rubygems: "${{ matrix.rubygems }}"
          bundler: "${{ matrix.bundler }}"
          bundler-cache: true

      - name: Tests
        run: bundle exec rake
